server:
  ssl:
    key-store: classpath:ondc.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: ondc
    key-password: password
  port: 8443
ehcache:
  cacheregion:
    beckn-api:
      common-cache:
        timetolive: 86400
        entrycount: 1000
      lookup-cache:
        timetolive: 1800
        entrycount: 1000
beckn:
  persistence:
    type: http
    audit-schema-error: true
    file-path: ./
  entity:
    type: seller
debug: true