server:
  port: 8082
ehcache:
  cacheregion:
    beckn-api:
      common-cache:
        timetolive: 86400
        entrycount: 1000
      lookup-cache:
        timetolive: 1800
        entrycount: 1000
beckn:
  persistence:
    type: http
    audit-schema-error: true
    file-path: ./
  entity:
    type: seller